

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: foodweb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ansh
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
      - "5001:5001"  # WebSocket port exposed
    depends_on:
      - postgres
    environment:
      PGUSER: postgres
      PGPASSWORD: ansh
      PGDATABASE: foodweb
      PGHOST: postgres
      PGPORT: 5432

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
